version: '3'
services:
  frontend:
    image: crud-empleados_frontend
    ports:
      - "5000:3000"
    networks:
      - app-network

  backend:
    image: crud-empleados_backend
    ports:
      - "4000:4000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
